name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      openshift_version:
        description: 'Enter the version.'
        required: true
        default: '4.18.0-okd-scos.10'
      latest_release:
        description: 'Set this buuild as latest release'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

permissions:
  actions:  write
  contents: read
  packages: write

env:
  VERSION: ${{ inputs.openshift_version }}

jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        image: ghcr.io/amitie10g/binfmt:latest
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: |
          image=ghcr.io/amitie10g/buildkit:master

    - name: Set tags metadata
      uses: docker/metadata-action@v5
      id: meta
      with:
        images: |
          ghcr.io/${{ github.repository_owner }}/openshift-install
        tags: |
          ${{ env.VERSION }}
          ${{ inputs.latest_release == 'true' && 'latest' || '' }}
    
    - name: Build And Push Docker Image
      uses: docker/build-push-action@v5
      id: build
      with:
        push: true
        build-args: |
          VERSION=${{ env.VERSION }}
        cache-to: type=inline
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
