name: Docker Image CI

on:
  workflow_dispatch:

permissions:
  actions:  write
  contents: read
  packages: write

env:
  VERSION: 4.19.0-okd-scos.3

jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        image: ghcr.io/amitie10g/binfmt:latest
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: |
          image=ghcr.io/amitie10g/buildkit:master

    - name: Get binaries
      run: |
        curl -LO https://github.com/okd-project/okd/releases/download/${VERSION}/openshift-client-linux-${VERSION}.tar.gz
        curl -LO https://github.com/okd-project/okd/releases/download/${VERSION}/openshift-install-linux-${VERSION}.tar.gz
        tar -xvf openshift-client-linux-${VERSION}.tar.gz
        tar -xvf openshift-install-linux-${VERSION}.tar.gz
        ls

    - name: Set tags metadata
      uses: docker/metadata-action@v5
      id: meta
      with:
        images: |
          ghcr.io/${{ github.repository_owner }}/openshift-installer-okd
    
    - name: Build And Push Docker Image
      uses: docker/build-push-action@v5
      id: build
      with:
        push: true
        build-args: |
          VERSION=${{ env.VERSION }}
        platforms: linux/amd64,linux/arm64
        cache-to: type=inline
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
